# Generated by Django 4.2 on 2024-05-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0004_society_total_buildings_alter_society_type_building'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='societies.society'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='member_type',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='owner', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('sub_admin', 'Sub Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='society',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Building', to='societies.society'),
            preserve_default=False,
        ),
    ]
