# Generated by Django 4.2 on 2024-05-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0005_alter_building_building_alter_building_name_and_more'),
        ('users', '0002_user_building_user_member_type_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='societies.building'),
        ),
        migrations.AlterField(
            model_name='user',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_name_buildings', to='societies.building'),
        ),
    ]
