# Generated by Django 4.2 on 2024-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name_plural': 'Societies'},
        ),
        migrations.AddField(
            model_name='society',
            name='total_bungalows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='total_flats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='type',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Building', 'Building'), ('Both', 'Both')], default='', max_length=10),
        ),
    ]
