# Generated by Django 4.2 on 2024-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_alter_society_options_society_total_bungalows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='type',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Building', 'Building'), ('Both', 'Both')], default='---', max_length=10),
        ),
    ]
