# Generated by Django 4.2 on 2024-05-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0004_society_total_buildings_alter_society_type_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='society',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
